const{test,expect}=require("@playwright/test")
const LoginPage=require('../Page/loginautomation')
const HomePage = require("../Page/Homepageautomation")
const testdata=JSON.parse(JSON.stringify(require("../Automationtestdata.json")))
test("Automation Project",async ({page})=>{
    const login=new LoginPage(page)
    const homepage=new HomePage(page)
    await page.goto("https://freelance-learn-automation.vercel.app/login")
    await login.login(testdata.username,testdata.password)
    await login.assertSignIn()
    await homepage.homePage()
    await homepage.assertSignOut()
})