const {test,expect}=require('@playwright/test')
//const testdata=JSON.parse(JSON.stringify(require("../testdata.json")))
test("User creation",async ({page})=> {
await page.goto("https://freelance-learn-automation.vercel.app/login")
await page.getByRole("link",{name:"New user? Signup"}).click()
await page.getByRole('textbox', { name: 'Name' }).fill("Ganesh")
await page.getByRole('textbox', { name: 'Email' }).fill("ganesh1@gmail.com")
await page.getByRole('textbox', { name: 'Password' }).fill("Summer@01")
await page.getByRole('checkbox',{name:"Azure"}).check()
await page.getByRole('checkbox',{name:"Selenium"}).check()
await page.getByRole('checkbox',{name:"Javascript"}).check()
await page.locator('#gender2').check()
await page.locator("#state").selectOption({label:"Tamil Nadu"})
await page.locator("#hobbies").selectOption(['Playing','Reading'])
await page.getByRole('button',{name:"sign up"}).click()
const errmsg=(await page.getByText("Email already registered!").textContent()).trim()
console.log(errmsg)
await expect(errmsg).toBe("Email already registered!")


})